import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import "./styles/theme.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "New Era Construction",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.variable} bg-background text-on-background min-h-screen`}>
        {children}
      </body>
    </html>
  );
}
